builds:
  - binary: carthage-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: carthage-cli
    homepage: https://github.com/Abdelwaeb-Hnaien/homebrew-carthage-cli
    tap:
      owner: Abdelwaheb-Hnaien
      name: homebrew-carthage-cli
    # commit_author:
    #   name: abdel
    #   email: abdelwaheb.hnaien@gmail.com

checksum:
  name_template: 'checksums.txt'
